CREATE TABLE  `PUBLIC_MESSAGES` (
    `ID` bigint(20) NOT NULL auto_increment,
    `DATE` datetime NOT NULL,
    `SENDER_ID` bigint(20) NOT NULL,
    `WORKOUT_ID` bigint(20),
    `CONTENT` TEXT character set utf8 NOT NULL,
    PRIMARY KEY  (`ID`),
    KEY `public_messages_sender_ID` USING BTREE (`SENDER_ID`),
    CONSTRAINT `public_messages_sender_fk` FOREIGN KEY (`SENDER_ID`) REFERENCES `USERS` (`ID`),
    KEY `public_messages_workout_ID` USING BTREE (`WORKOUT_ID`),
    CONSTRAINT `public_messages_workout_fk` FOREIGN KEY (`WORKOUT_ID`) REFERENCES `WORKOUTS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

BEGIN transaction;
INSERT `PUBLIC_MESSAGES` (DATE, SENDER_ID, WORKOUT_ID, CONTENT)
    SELECT DATE, SENDER_ID, WORKOUT_ID, CONTENT FROM MESSAGES WHERE RECEIVER_ID IS NULL; 
DELETE FROM `MESSAGES` WHERE RECEIVER_ID IS NULL;
commit;
ALTER TABLE `MESSAGES` MODIFY COLUMN `RECEIVER_ID` BIGINT(20) NOT NULL;