CREATE TABLE  `WORKOUT_USER` (
    `USER_ID` bigint(20) NOT NULL,
    `WORKOUT_ID` bigint(20),
    PRIMARY KEY  (`USER_ID`, `WORKOUT_ID`),
    KEY `workout_user_user_ID` USING BTREE (`USER_ID`),
    CONSTRAINT `workout_user_user_fk` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`),
    KEY `workout_user_workout_ID` USING BTREE (`WORKOUT_ID`),
    CONSTRAINT `workout_user_workout_fk` FOREIGN KEY (`WORKOUT_ID`) REFERENCES `WORKOUTS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO  `WORKOUT_USER` (`USER_ID`, `WORKOUT_ID`) SELECT USER_ID, ID FROM WORKOUTS;