ALTER TABLE `USERS` ADD COLUMN `NIKEPLUSEMAIL` varchar(255) DEFAULT NULL;
ALTER TABLE `USERS` ADD COLUMN `NIKEPLUSPASSWORD` varchar(255) DEFAULT NULL;
ALTER TABLE `WORKOUTS` ADD COLUMN `NIKEPLUSID` varchar(20) DEFAULT NULL;
ALTER TABLE `WORKOUTS` ADD UNIQUE KEY `nike_plus_ID` USING BTREE (`NIKEPLUSID`);