CREATE TABLE `TRACKS` (
    `ID` bigint(20) NOT NULL auto_increment,
    `CREATION_DATE` TIMESTAMP NOT NULL,
    `OWNER_ID` bigint(20) NOT NULL,
    `POINTS` VARCHAR(20000) character set utf8 NOT NULL,
    `LENGTH` DOUBLE NOT NULL,
    PRIMARY KEY  (`ID`),
    KEY `track_owner_ID` USING BTREE (`OWNER_ID`),
    CONSTRAINT `track_owner_fk` FOREIGN KEY (`OWNER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
