ALTER TABLE `TRACKS` ADD COLUMN `TITLE` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `WORKOUTS` ADD COLUMN `TRACK_ID` bigint(20) DEFAULT NULL;

ALTER TABLE `WORKOUTS` ADD KEY `workouts_track_ID` USING BTREE (`TRACK_ID`);
ALTER TABLE `WORKOUTS` ADD CONSTRAINT `workouts_track_fk` FOREIGN KEY (`TRACK_ID`) REFERENCES `TRACKS` (`ID`);
